[package]
name = "movie-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version="0.4.41", features = ["serde"] }
regex = "1.11.1"
reqwest = {version = "0.12.15", features = ["blocking", "rustls-tls"] }
scraper = "0.23.1"
